FROM golang:1.14.2

RUN mkdir /app
WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

RUN ["go", "get", "github.com/githubnemo/CompileDaemon"]

COPY . .

ENTRYPOINT CompileDaemon -log-prefix=false -build="go build -o bin/application cmd/api/main.go" -command="./bin/application -dev"